"""create users table

Revision ID: 0001
Revises: 
Create Date: 2025-06-18 16:21:53.869812

"""
import hashlib
from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table(
        'users',
        sa.Column('id', sa.Integer, primary_key=True, nullable=False, autoincrement=True),
        sa.Column('email', sa.String, unique=True, nullable=False),
        sa.Column('password', sa.String),
        sa.Column('user_name', sa.String),
        sa.Column('first_name', sa.String),
        sa.Column('last_name', sa.String),
        sa.Column('is_active', sa.Boolean, server_default=sa.text('True')),
        sa.Column('activated_at', sa.DateTime),
        sa.Column('is_admin', sa.Boolean, server_default=sa.text('False')),
        sa.Column('token', sa.String),
        sa.Column('token_send_time', sa.DateTime),
        sa.Column('created_at', sa.DateTime),
        sa.Column('updated_at', sa.DateTime, server_default=sa.text('now()'), default=datetime.now()),
    )
    op.bulk_insert(users_table,
                   [
                       {
                           'email': 'admin@example.com', 'user_name': 'admin', 'is_admin': True,
                           'password': hashlib.sha256('123456'.encode('utf-8')).hexdigest(),
                           'created_at': datetime.now(),
                       },
                   ])
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('users')
